[package]
name = "material"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-sphincsplus = { version = "0.7.0", features = ["avx2"] }
pqcrypto-traits = "0.3.5"
hex = "0.4.3"
rand = "0.8.5"
# bs58 = "0.5.1"
