[package]
name = "state-sdk"
edition = "2021"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cesium-contract-sdk.workspace = true
cesium-contract-sdk-macros.workspace = true