[package]
name = "cesium-material"
edition = "2021"
version.workspace = true
license = "GPL-3.0"
publish = false


[dependencies]
pqcrypto-sphincsplus.workspace = true
pqcrypto-traits.workspace = true
hex.workspace = true
rand.workspace = true
bs58.workspace = true
serde.workspace = true