[package]
name = "cli"
edition = "2021"
version.workspace = true
license = "GPL-3.0"
publish = false

[[bin]]
name = "cesium"
path = "src/main.rs"


[dependencies]
clap.workspace = true
jsonrpsee = { workspace = true, features = ["http-client", "ws-client", "macros"]}