[package]
name = "cesium-storage"
edition = "2021"
version.workspace = true
license = "GPL-3.0"
publish = false

[dependencies]
cesium-crypto.workspace = true
rocksdb.workspace = true
tokio.workspace = true
once_cell.workspace = true