[package]
name = "cesium-storage"
edition = "2021"
version.workspace = true
license = "GPL-3.0"
publish = false


[dependencies]
cesium-material.workspace = true
rocksdb.workspace = true
# tokio.workspace = true
bincode.workspace = true
serde.workspace = true
tempfile.workspace = true