[package]
name = "selenide-sdk-macros"
edition = "2021"
version.workspace = true
license = "GPL-3.0"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] } 
proc-macro2 = "1.0"