[package]
name = "cesium-runtime"
edition = "2021"
version.workspace = true
license = "GPL-3.0"
publish = false


[dependencies]
wasmedge-sdk.workspace = true
wasmedge-sys.workspace = true
cesium-material.workspace = true
wasmparser.workspace = true