name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install WasmEdge
      run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
    - name: Source WasmEdge environment file
      run: source $HOME/.wasmedge/env
    - name: Rustup target
      run: rustup target add wasm32-wasi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
