name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"  # Treats warnings as errors

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install WasmEdge
      run: |
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
        source $HOME/.wasmedge/env
        echo "$HOME/.wasmedge/bin" >> $GITHUB_PATH
        echo "$HOME/.wasmedge/lib" >> $GITHUB_ENV


    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Add WASM target
      run: rustup target add wasm32-wasi

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Check formatting
      run: cargo fmt --all -- --check

    # - name: Lint
    #   run: cargo clippy -- -D warnings

    - name: Build
      run: make

    - name: Run tests
      env:
        LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}:$HOME/.wasmedge/lib
      run: make test